Update README.md
hacklanta/lift-formality pull request #31
Opened 2019-01-18 04:29 UTC by ChrisHagan

Added some detailing around how to treat a fileUpload in an ajax context, as well as how to treat it as optional without failing the validation.

No changes to code.

2019-01-26 02:04 UTC, Shadowfiend requested changes
Great additions! Left a couple of comments on syntax and a touch on style.

2019-01-26 02:04 UTC, Shadowfiend commented on README.md
> +javascript```
This doesn't render quite right; it should be “```javascript”.

2019-01-26 02:04 UTC, Shadowfiend commented on README.md
> +(Adapted from [https://github.com/Shadowfiend/lift-ajax-file-upload-example/blob/master/src/main/webapp/static/js/fileUpload.js])
Perhaps `Adapted from [this example](link).`?

2019-01-26 02:04 UTC, Shadowfiend commented on README.md
> +                // do not use attr() to set name. IE7 will hate this: http://stackoverflow.com/questions/2105815/weird-behaviour-of-iframe-name-attribute-set-by-jquery-in-ie
This can probably go the way of the dodo nowadays, but why not :)

2019-01-26 02:04 UTC, Shadowfiend commented on README.md
> +You may also wish to treat your uploaded files as optional.  By default, a fileUploadField will fail validation if not provided.
How about combining this and the next paragraph, like so:

```
You may also wish to treat your uploaded files as optional. By default,
however, a `fileUploadField` will fail validation if no file is provided by
the user. You can make the field(s) optional through conversion into an
`Option`:
```

Thoughts?

2019-01-26 02:04 UTC, Shadowfiend commented on README.md
> +scala```
Same as above, should be “```scala”.

2019-01-26 05:56 UTC, ChrisHagan reviewed
Incorporated all suggested changes.  Thanks Antonio!

2019-02-03 01:04 UTC, Shadowfiend approved these changes
Looks good, let's rock 'n roll!

2019-02-03 01:05 UTC, merged